let GET_USERS = 'GET_USERS';
let GET_USER = 'GET_USER';
let ADD_USER = 'ADD_USER';
let UPDATE_USER = 'UPDATE_USER';
let DELETE_USER = 'DELETE_USER';

let ADD_TRANSACTION = 'ADD_TRANSACTION';
let GET_TRANSACTIONS = 'GET_TRANSACTIONS';
let GET_TRANSACTION = 'GET_TRANSACTION';
let UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
let FILTER_TRANSACTION = 'FILTER_TRANSACTION';
let DELETE_TRANSACTION = 'DELETE_TRANSACTION';

let LOGIN = 'LOGIN';
let LOGOUT = 'LOGOUT';
let CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export {GET_USERS, GET_USER, ADD_USER, UPDATE_USER, DELETE_USER, ADD_TRANSACTION, GET_TRANSACTIONS, GET_TRANSACTION, UPDATE_TRANSACTION, FILTER_TRANSACTION, DELETE_TRANSACTION, LOGIN, LOGOUT, CHANGE_PASSWORD}


